name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  static-code-analysis:
    # Run prettier:check and lint in all repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - name: Perform static code analysis 🔬
        run: bash static-code-analysis.sh

  build:
    # Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - name: Build client 🛠
        run: bash build.sh

  # test:
  #   # Run unit tests in all repos
  #   runs-on: ubuntu latest
  #   steps:
  #     - uses: actions/checkout@v2
